# Generated by Django 4.1.3 on 2022-11-23 18:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videosmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosmodel',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
